local path = minetest.get_modpath("mobs")
dofile(path.."/api.lua")
dofile(path.."/egg.lua")
dofile(path.."/dog.lua")
dofile(path.."/cat.lua")
dofile(path.."/sheep.lua")
dofile(path.."/dragon.lua")
dofile(path.."/fox.lua")
dofile(path.."/tortoise.lua")
dofile(path.."/knight.lua")
dofile(path.."/monsterx1.lua")