name = tutorial
description = Regnum mod: tutorial
depends = default, pipeworks, mesecons_lightstone, mesecons_hydroturbine, mesecons_solarpanel, mesecons_noteblock, mesecons_movestones, mesecons_lamp, mesecons_detector, mesecons_commandblock, mesecons_materials, mesecons_pressureplates, mesecons_torch, mesecons_microcontroller, mesecons_stickyblocks, mesecons_blinkyplant, technic, concrete, extranodes, mobs
