print("[Army] Loading....")
dofile(minetest.get_modpath("army").."/chainlink.lua")
print("[Camo] Chainlink Fence loaded!")
dofile(minetest.get_modpath("army").."/camouflage.lua")
print("[Camo] Camouflage Fence loaded!")
dofile(minetest.get_modpath("army").."/sandbag.lua")
print("[Camo] Sandbag loaded!")
dofile(minetest.get_modpath("army").."/barbedwire.lua")
print("[Camo] Barbed Wire loaded!")
dofile(minetest.get_modpath("army").."/light.lua")
print("[Camo] Lights loaded!")
dofile(minetest.get_modpath("army").."/airdrop.lua")
print("[Camo] Airdrop loaded!")
dofile(minetest.get_modpath("army").."/ration.lua")
print("[Camo] Rations loaded!")
dofile(minetest.get_modpath("army").."/gun.lua")
print("[Camo] Gun loaded!")
dofile(minetest.get_modpath("army").."/bullet.lua")
print("[Camo] Bullet loaded!")
dofile(minetest.get_modpath("army").."/knife.lua")
print("[Camo] Knife loaded!")
print("[Army] Army Mod Fully Loaded!")
